{"metadata":{"kernelspec":{"language":"python","display_name":"Python 3","name":"python3"},"language_info":{"name":"python","version":"3.10.12","mimetype":"text/x-python","codemirror_mode":{"name":"ipython","version":3},"pygments_lexer":"ipython3","nbconvert_exporter":"python","file_extension":".py"},"kaggle":{"accelerator":"none","dataSources":[],"dockerImageVersionId":30822,"isInternetEnabled":false,"language":"python","sourceType":"notebook","isGpuEnabled":false}},"nbformat_minor":4,"nbformat":4,"cells":[{"cell_type":"code","source":"# This Python 3 environment comes with many helpful analytics libraries installed\n# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python\n# For example, here's several helpful packages to load\n\nimport numpy as np # linear algebra\nimport pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)\n\n# Input data files are available in the read-only \"../input/\" directory\n# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory\n\nimport os\nfor dirname, _, filenames in os.walk('/kaggle/input'):\n    for filename in filenames:\n        print(os.path.join(dirname, filename))\n\n# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using \"Save & Run All\" \n# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session","metadata":{"_uuid":"8f2839f25d086af736a60e9eeb907d3b93b6e0e5","_cell_guid":"b1076dfc-b9ad-4769-8c92-a6c4dae69d19","trusted":true},"outputs":[],"execution_count":null},{"cell_type":"code","source":"!pip install swig","metadata":{"trusted":true,"execution":{"iopub.status.busy":"2024-12-22T14:08:01.113023Z","iopub.execute_input":"2024-12-22T14:08:01.113385Z","iopub.status.idle":"2024-12-22T14:11:22.772240Z","shell.execute_reply.started":"2024-12-22T14:08:01.113319Z","shell.execute_reply":"2024-12-22T14:11:22.770959Z"}},"outputs":[{"name":"stdout","text":"\u001b[33mWARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7c90b9f4b220>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/swig/\u001b[0m\u001b[33m\n\u001b[0m\u001b[33mWARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7c90b9f4b5b0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/swig/\u001b[0m\u001b[33m\n\u001b[0m\u001b[33mWARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7c90b9f4ba90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/swig/\u001b[0m\u001b[33m\n\u001b[0m\u001b[33mWARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7c90b9f4bc70>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/swig/\u001b[0m\u001b[33m\n\u001b[0m\u001b[33mWARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7c90b9f4be50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/swig/\u001b[0m\u001b[33m\n\u001b[0m\u001b[31mERROR: Could not find a version that satisfies the requirement swig (from versions: none)\u001b[0m\u001b[31m\n\u001b[0m\u001b[31mERROR: No matching distribution found for swig\u001b[0m\u001b[31m\n\u001b[0m","output_type":"stream"}],"execution_count":1},{"cell_type":"code","source":"!pip install stable-baselines3[extra]","metadata":{"trusted":true,"execution":{"iopub.status.busy":"2024-12-22T14:38:17.248377Z","iopub.execute_input":"2024-12-22T14:38:17.248909Z"}},"outputs":[{"name":"stderr","text":"/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.\n  and should_run_async(code)\n/usr/lib/python3.10/pty.py:89: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.\n  pid, fd = os.forkpty()\n","output_type":"stream"},{"name":"stdout","text":"Requirement already satisfied: stable-baselines3[extra] in /usr/local/lib/python3.10/dist-packages (2.1.0)\nRequirement already satisfied: gymnasium<0.30,>=0.28.1 in /usr/local/lib/python3.10/dist-packages (from stable-baselines3[extra]) (0.29.0)\nRequirement already satisfied: numpy>=1.20 in /usr/local/lib/python3.10/dist-packages (from stable-baselines3[extra]) (1.26.4)\nRequirement already satisfied: torch>=1.13 in /usr/local/lib/python3.10/dist-packages (from stable-baselines3[extra]) (2.4.1+cu121)\nRequirement already satisfied: cloudpickle in /usr/local/lib/python3.10/dist-packages (from stable-baselines3[extra]) (3.1.0)\nRequirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from stable-baselines3[extra]) (2.1.4)\nRequirement already satisfied: matplotlib in /usr/local/lib/python3.10/dist-packages (from stable-baselines3[extra]) (3.7.1)\nRequirement already satisfied: opencv-python in /usr/local/lib/python3.10/dist-packages (from stable-baselines3[extra]) (4.10.0.84)\nRequirement already satisfied: pygame in /usr/local/lib/python3.10/dist-packages (from stable-baselines3[extra]) (2.6.0)\nRequirement already satisfied: tensorboard>=2.9.1 in /usr/local/lib/python3.10/dist-packages (from stable-baselines3[extra]) (2.17.0)\nRequirement already satisfied: psutil in /usr/local/lib/python3.10/dist-packages (from stable-baselines3[extra]) (5.9.5)\nRequirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from stable-baselines3[extra]) (4.66.5)\nRequirement already satisfied: rich in /usr/local/lib/python3.10/dist-packages (from stable-baselines3[extra]) (13.8.1)\n\u001b[33mWARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7da2fa998b20>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/shimmy/\u001b[0m\u001b[33m\n\u001b[0m\u001b[33mWARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7da2fa998e50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/shimmy/\u001b[0m\u001b[33m\n\u001b[0m\u001b[33mWARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7da2fa9991b0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/shimmy/\u001b[0m\u001b[33m\n\u001b[0m\u001b[33mWARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7da2fa999360>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/shimmy/\u001b[0m\u001b[33m\n\u001b[0m\u001b[33mWARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7da2fa999510>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/shimmy/\u001b[0m\u001b[33m\n\u001b[0mINFO: pip is looking at multiple versions of stable-baselines3[extra] to determine which version is compatible with other requirements. This could take a while.\n\u001b[33mWARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7da2fa962b30>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/stable-baselines3/\u001b[0m\u001b[33m\n\u001b[0m","output_type":"stream"}],"execution_count":null},{"cell_type":"code","source":"!pip install gymnasium[\"all\"]","metadata":{"trusted":true},"outputs":[],"execution_count":null},{"cell_type":"code","source":"import gymnasium as gym\nimport numpy as np\nimport matplotlib.pyplot as plt\nfrom stable_baselines3 import PPO\nfrom stable_baselines3.common.evaluation import evaluate_policy\nfrom stable_baselines3.common.callbacks import BaseCallback\nfrom stable_baselines3.common.env_util import make_vec_env","metadata":{"trusted":true},"outputs":[],"execution_count":null},{"cell_type":"code","source":"class PlotCallback(BaseCallback):\n    def __init__(self, verbose=0):\n        super().__init__(verbose)\n        self.rewards = []\n        self.losses = []\n        self.returns = []\n\n    def _on_step(self) -> bool:\n        if hasattr(self.model, 'logger'):\n            loss = self.model.logger.name_to_value.get('train/loss', np.nan)\n            if not np.isnan(loss):\n                self.losses.append(loss)\n        return True\n\n    def _on_rollout_end(self) -> None:\n        # Log rewards and calculate returns at the end of each episode\n        if hasattr(self.model, 'ep_info_buffer') and self.model.ep_info_buffer:\n            for ep_info in self.model.ep_info_buffer:\n                self.rewards.append(ep_info['r'])\n\n        self.model.ep_info_buffer.clear()","metadata":{"trusted":true},"outputs":[],"execution_count":null},{"cell_type":"code","source":"env = gym.make('Pusher-v5')","metadata":{"trusted":true},"outputs":[],"execution_count":null},{"cell_type":"code","source":"gamma = 0.99\nlearning_rate = 0.0001","metadata":{"trusted":true},"outputs":[],"execution_count":null},{"cell_type":"code","source":"# implement td3 on pusher\nfrom stable_baselines3 import TD3","metadata":{"trusted":true},"outputs":[],"execution_count":null},{"cell_type":"code","source":"model = TD3('MlpPolicy', env, verbose=1, gamma=gamma, learning_rate=learning_rate)","metadata":{"trusted":true},"outputs":[],"execution_count":null},{"cell_type":"code","source":"callback = PlotCallback()\ntraining_history = model.learn(total_timesteps=200000, callback=callback, log_interval=1000)","metadata":{"trusted":true},"outputs":[],"execution_count":null},{"cell_type":"code","source":"from matplotlib import pyplot as plt\n\nplt.figure(figsize=(12, 6))\nplt.subplot(1, 2, 2)\nplt.plot(callback.rewards, label=\"Returns\")\nplt.xlabel(\"Episode\")\nplt.ylabel(\"Total Reward\")\n\nplt.legend()\n\nplt.tight_layout()\nplt.show()\n","metadata":{"trusted":true},"outputs":[],"execution_count":null},{"cell_type":"code","source":"model.save(\"td3_pusher1\")","metadata":{"trusted":true},"outputs":[],"execution_count":null}]}